<section>
  <header class="organiser-races-header">
    <h1>My races</h1>
    <nav-button view="organise/create">
      Create a race
      <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-circle-plus-icon lucide-circle-plus"><circle cx="12" cy="12" r="10"/><path d="M8 12h8"/><path d="M12 8v8"/></svg>
    </nav-button>
  </header>
  <section class="organiser-races-container">
    <organiser-races></organiser-races>
  <section>
</section>